# Generated by Django 4.2.6 on 2023-12-06 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="uuid",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20),
        ),
    ]
