# Generated by Django 4.2.6 on 2023-12-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_alter_room_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="uuid",
            new_name="code",
        ),
    ]
