# Generated by Django 4.2.6 on 2023-12-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0008_room_videocode_alter_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(default="y3OuMj", max_length=20),
        ),
    ]
